# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13DyryaHE1eidmYJmXDpIAMtoi7drxbYX
"""

import streamlit as st
import requests
from PIL import Image
from io import BytesIO

# Exibir o logo da empresa
logo_url = "https://natcofarma.com/wp-content/webp-express/webp-images/uploads/2021/07/Logo-NatcoFarma.png.webp"
response = requests.get(logo_url)
logo = Image.open(BytesIO(response.content))
st.image(logo, caption="NatcoFarma", use_column_width=True)

# Título do site
st.title("Portal de Pesquisa - LILACS, SciELO e PubMed")

# Campo de busca
query = st.text_input("Digite o termo de busca:", placeholder="Digite aqui...")

# Funções para buscar nos bancos de dados
def search_lilacs(query):
    url = f"https://pesquisa.bvsalud.org/portal/?q={query}&index=lilacs"
    return url

def search_scielo(query):
    url = f"https://search.scielo.org/?q={query}&lang=pt"
    return url

def search_pubmed(query):
    url = f"https://pubmed.ncbi.nlm.nih.gov/?term={query}"
    return url

# Exibir os resultados da busca
if query:
    st.subheader("Resultados de Pesquisa:")
    st.write(f"**Termo pesquisado**: {query}")

    # Links para os resultados de cada banco de dados
    st.markdown("### Resultados por Base de Dados:")

    # LILACS
    lilacs_url = search_lilacs(query)
    st.markdown(f"- [Resultados no LILACS]({lilacs_url})")

    # SciELO
    scielo_url = search_scielo(query)
    st.markdown(f"- [Resultados no SciELO]({scielo_url})")

    # PubMed
    pubmed_url = search_pubmed(query)
    st.markdown(f"- [Resultados no PubMed]({pubmed_url})")

    st.write("Clique em qualquer link para ver os resultados diretamente no site correspondente.")
else:
    st.write("Digite um termo de busca acima para começar.")